### ISSUE TITLE
Inconsistent content

### ISSUE THREAD

**Issue by DwijBavisi** [TaciturnCoder/Consortium#4]
Missing line: [issue] vs [origin]

[origin]: https://github.com/TaciturnCoder/TCsL2H/blob/5f8a142f7ed4ceb6955538528fc425195d0e3128/docs/legalcode/0.0.1.md?plain=1#L33
[issue]: https://github.com/TaciturnCoder/Consortium/blob/bbf8273110478469db14715b5e375c107a99e731/TCsL2H.md?plain=1#L32

**Comment by TaciturnCoder** [comment]
Solved with pull request #5
